### ISSUE TITLE
Incorrect gym implementation

### ISSUE THREAD

**Issue by jkulhanek** [activatedgeek/gym-2048#2]
Hi, thanks for a great environment. However, your environment does not implement the gym interface correctly. You need to return the rendered maze from your reset method.

**Comment by jkulhanek** [comment]
Why is this closed?

**Comment by activatedgeek** [comment]
Hey @jkulhanek, thanks for discovering that. I have fixed it now :grinning:

**Comment by jkulhanek** [comment]
Sure, thanks :)

**Comment by activatedgeek** [comment]
@jkulhanek The new version has also been published to PyPI. So an upgrade should get you version 0.2.6. Let me know if it doesn't work as intended.
